In [13]:
import sys, os
sys.path.insert(0, os.path.abspath('..'))

import pyodbc
import helpers.db as db     
import queries
import pandas as pd
from helpers import show_balance_result

conn = db.get_connection()
df = pd.read_sql(queries.get_total_balance_query(), conn)
df

C:\Users\Sajjad Hussain\AppData\Local\Temp\ipykernel_29884\3261316077.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(queries.get_total_balance_query(), conn)

     TotalDebit   TotalCredit
0  2.788125e+11  2.788124e+11

In [14]:
tolerance=0.01
total_debit = df.loc[0, "TotalDebit"]
total_credit = df.loc[0, "TotalCredit"]

if abs(total_debit - total_credit) > tolerance:
    show_balance_result(df, "reports")
else:
    show_balance_result(pd.DataFrame(), "reports")

     TotalDebit   TotalCredit
0  2.788125e+11  2.788124e+11

In [15]:
dfBranch = pd.read_sql(queries.get_branch_balance_query(), conn)
tolerance = 0.01

unbalanced_branches = dfBranch.loc[
    dfBranch["Difference"].abs() > tolerance,
    ["BranchId", "TotalDebit", "TotalCredit", "Difference"]
].copy()

show_balance_result(unbalanced_branches, "branches")

C:\Users\Sajjad Hussain\AppData\Local\Temp\ipykernel_29884\1075636757.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dfBranch = pd.read_sql(queries.get_branch_balance_query(), conn)

   BranchId    TotalDebit   TotalCredit  Difference
0         1  2.788125e+11  2.788124e+11  136030.197

In [16]:
dfBranchCurrency = pd.read_sql(queries.get_branch_currency_balance_query(), conn)
unbalanced_branch_currency = dfBranchCurrency.loc[
    (dfBranchCurrency["TotalDebit"] - dfBranchCurrency["TotalCredit"]).abs() > tolerance,
    ["BranchId", "CurrencyId", "TotalDebit", "TotalCredit"]
].copy()

if unbalanced_branch_currency.empty:
    show_balance_result(unbalanced_branch_currency, "all branch-currency records")
else:
    unbalanced_branch_currency["Difference"] = (
        unbalanced_branch_currency["TotalDebit"] - unbalanced_branch_currency["TotalCredit"]
    )
    show_balance_result(unbalanced_branch_currency, "unbalanced branch-currency records")

C:\Users\Sajjad Hussain\AppData\Local\Temp\ipykernel_29884\3515977355.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dfBranchCurrency = pd.read_sql(queries.get_branch_currency_balance_query(), conn)

   BranchId  CurrencyId    TotalDebit   TotalCredit    Difference
0         1          77  2.682642e+11  2.686157e+11 -3.514851e+08
6         1          78  1.054830e+10  1.019668e+10  3.516211e+08

In [17]:
dfBranchCurrencyYear = pd.read_sql(queries.get_branch_currency_year_balance_query(), conn)
unbalanced_branch_currency_year = dfBranchCurrencyYear.loc[
    (dfBranchCurrencyYear["TotalDebit"] - dfBranchCurrencyYear["TotalCredit"]).abs() > tolerance,
    ["BranchId", "CurrencyId", "YearId", "TotalDebit", "TotalCredit"]
].copy()

if unbalanced_branch_currency_year.empty:
    show_balance_result(unbalanced_branch_currency_year, "all branch-currency-year records")
else:
    unbalanced_branch_currency_year["Difference"] = (
        unbalanced_branch_currency_year["TotalDebit"] - unbalanced_branch_currency_year["TotalCredit"]
    )
    show_balance_result(unbalanced_branch_currency_year, "unbalanced branch-currency-year records")

C:\Users\Sajjad Hussain\AppData\Local\Temp\ipykernel_29884\4039351765.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dfBranchCurrencyYear = pd.read_sql(queries.get_branch_currency_year_balance_query(), conn)

    BranchId  CurrencyId  YearId    TotalDebit   TotalCredit    Difference
0          1          77       4  1.515934e+10  1.516571e+10 -6.371101e+06
1          1          77       5  1.713881e+10  1.712676e+10  1.205232e+07
2          1          77      11  6.215998e+10  6.235446e+10 -1.944735e+08
3          1          77      12  9.441535e+10  9.459917e+10 -1.838280e+08
4          1          77      13  7.781213e+10  7.780560e+10  6.531027e+06
5          1          77      14  1.570559e+09  1.555955e+09  1.460424e+07
6          1          78       5  3.182880e+08  3.239314e+08 -5.643475e+06
7          1          78      11  3.455209e+09  3.260637e+09  1.945718e+08
8          1          78      12  5.549342e+09  5.365514e+09  1.838280e+08
9          1          78      13  1.119296e+09  1.125827e+09 -6.531027e+06
10         1          78      14  1.061625e+08  1.207667e+08 -1.460424e+07